### ISSUE TITLE
ER_NO_SUCH_TABLE: Table 'db.sys_entity' doesn't exist

### ISSUE THREAD

**Issue by sdbondi** [senecajs/seneca-entity#4]
I'm sure I'm missing something silly here, but `seneca-entity` seems to want a table in the database.
I cannot find the schema of that table or any documentation on what is required by seneca-entity (with a mysql-store).

```text
Error: ER_NO_SUCH_TABLE: Table 'db.sys_entity' doesn't exist
api-service-0     at Query.Sequence._packetToError (/app/src/services/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
api-service-0     at Query.ErrorPacket (/app/src/services/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
api-service-0     at Protocol._parsePacket (/app/src/services/node_modules/mysql/lib/protocol/Protocol.js:274:23)
api-service-0     at Parser.write (/app/src/services/node_modules/mysql/lib/protocol/Parser.js:77:12)
api-service-0     at Protocol.write (/app/src/services/node_modules/mysql/lib/protocol/Protocol.js:39:16)
api-service-0     at Socket.<anonymous> (/app/src/services/node_modules/mysql/lib/Connection.js:96:28)
```

EDIT: It occurs to me that this is probably the `seneca-user` plugin

**Comment by sdbondi** [comment]
Yup, there is an issue relating to this over here: https://github.com/senecajs/seneca-user/issues/13 
I'll close.
